- .github/workflows/prepare-publish.yml
This is on top of https://github.com/getsentry/spotlight/pull/21
This adds a workflow that can be triggered, which will open a PR with all the changesets consumed & versions bumped accordingly.
For now, merging this PR will not do anything. But in a follow up to this, I'll add another action that is triggered when this PR is merged into main, which will actually run the npm publish automatically.
So the flow would be, overall:
1. Include changesets in each PR
2. When we want to cut a release, trigger the `Prepare Publish` GHA workflow
3. This will create a PR that needs to be approved & merged
4. When the PR is merged, the npm publish will happen automatically
> build: Add Github Action to prepare a publish

- .github/workflows/publish.yml
- package.json
This PR ensures that if the PRs generated by changeset are merged, we automatically publish to NPM.
I check this in three ways:
* Push to main only
* Push changing a `CHANGELOG.md` file
* The pushed commit has the message `meta(changelog): Update package versions` - this has to be kept in sync with the commit messages generated in the prepare-publish workflow.
Not sure if that is "bullet proof" enough, or if we need/can have more checks there 🤔 I think for now it should suffice, at least, and have very little room for misuse (worst case something that is on main is published "too early", as you can only publish off main).
I added a `NPM_TOKEN` secret to this repository.
> build: Publish on push to main

- packages/core/src/App.tsx
- packages/core/src/components/Overview.tsx
- packages/core/src/components/Tabs.tsx
- packages/core/src/components/Trigger.tsx
- packages/core/src/integrations/console/index.ts
- packages/core/src/integrations/integration.ts
- packages/core/src/integrations/sentry/data/sentryDataCache.ts
- packages/core/src/integrations/sentry/index.ts
- packages/core/src/sidecar.ts
- packages/core/src/types.ts
- packages/website/src/spotlight/snippets.ts
This causes a (breaking) change in the integrations API: `tabs` will now be a function returning arrays. This function will always be called when spotlight rerenders (i.e. when a new event is sent to spotlight). By doing this, users can update the notification count for each tab individually. The count can be inferred from the passed tab context which holds the integration data (i.e. the integration's events). 
In addition this PR als re-introduces the global trigger button notification notification counter in a general manner. For this, users can specify if a processed event is "severe". In case of a severe event, the global counter's style will be changed to red. This is the generalization of how the counter appearance was previously dependent on the presence of sentry errpors (which …
> ref(integrations): Make tabs functional to restore notification counts

- .changeset/funny-adults-glow.md
- .changeset/rare-ladybugs-rescue.md
- packages/core/src/App.tsx
- packages/core/src/components/Debugger.tsx
- packages/core/src/components/Overview.tsx
- packages/core/src/integrations/console/console-tab.tsx
- packages/core/src/integrations/console/index.ts
- packages/core/src/integrations/integration.ts
- packages/core/src/integrations/sentry/data/sentryDataCache.ts
- packages/core/src/integrations/sentry/index.ts
- packages/core/src/sidecar.ts
- packages/website/src/spotlight/snippets.ts
This PR refactors how we internally pass integration event data to integrations and how they can produce and interact with that data.
* Internally, we still populate the reactive `integrationData` map but now it maps from integration to a list of processed events
* Integrations' `tabs` hook, as well as the `tabContent` react component receive a `processedEvents` array that only contains the integration's events. 
* the `processEvent` hook returns now a container for the processed event with additional metadata for spotlight. Currently this includes the `severity` property to support the trigger button's notification count badge 
ref #19
> ref(integrations): Refactor `processEvent` and tab content props

- .changeset/real-impalas-grab.md
- packages/astro/src/index.ts
- packages/astro/src/snippets.ts
We cannot access core from a snippet because that is injected into the host app, which does not have access to dependencies dependencies.
> fix(spotlight): Re-export core from astro package

- .changeset/flat-mayflies-hang.md
- packages/astro/src/overlay/index.ts
- packages/astro/src/snippets.ts
- packages/core/src/App.tsx
- packages/core/src/index.tsx
- packages/website/package.json
- pnpm-lock.yaml
This PR finally fixes the toolbar button state by 
* exposing dedicated open and close APIs
* exposing an onClose callback
* bumping Astro to the latest version and adapting the breaking toolbar API changes
* invoking the newly added [`toggle-plugin`](https://docs.astro.build/en/reference/dev-overlay-plugin-reference/#toggle-plugin) event to reset the button state
Also did some more cleanup of leftover console logs
> fix(astro): Reset button state correctly

- packages/astro/src/index.ts
- packages/astro/src/snippets.ts
- packages/core/src/index.tsx
- packages/core/src/types.ts
- packages/playground/astro.config.mjs
- packages/playground/src/pages/ssr-error/index.astro
This PR adds Spotlight to error pages that are generated by Vite if a server-side error occurs that hinders the actual project content from being rendered on the client (e.g. SSR errors that let ssr fail). Previously, these pages didn't get spotlight because spotlight was only included in Astro's client page code. 
With this change, we now also inject ourselves into the error page bundle by:
* Adding a Vite plugin that transforms Vite's `client.js` script (which is always included, also in error pages) so that
* we check if Vite's error overlay should be shown
* we hook ourselves into Vite's websocket connection and listen for error events (the same error events that trigger the error overlay)
* in case of an error event, we initialize spotlight and inject it into the page
This required …
> feat(astro): Inject Spotlight into Error Pages

- .changeset/red-rivers-grin.md
- packages/astro/package.json
- packages/astro/src/index.ts
- packages/astro/src/snippets.ts
- packages/astro/src/vite/error-page.ts
- packages/astro/src/vite/source-context.ts
- packages/core/src/integrations/sentry/index.ts
- packages/core/src/integrations/sentry/sentry-integration.ts
- packages/playground/sentry.client.config.ts
- packages/playground/src/components/svelte/SvelteIsland.svelte
- pnpm-lock.yaml
This PR adds a mechanism to symbolicate client-side errors such as errors thrown within Astro islands and add source context from the original source files. 
More specifically, this PR adds two elements to Spotlight:
1. [core] A new `Spotlight` Sentry integration which is added to the SDK when the `sentry()` integration for spotlight is initialized
2. [astro] A new Vite plugin that opens an endpoint on the dev server. This endpoint accepts a stacktrace in form of a Sentry exception stacktrace, tries to resolve the source map, and, if successful, returns a stack trace with:
* Adjusted lineno and colno
* Added context line (the line +/- 5 lines around it)
Here's how it works:
1. Sentry client SDK is initialized
2. Spotlight initializes and adds the `Spotlight` integration to the Sentry SDK …
> feat(astro): Add dev mode sourcemaps resolver Vite plugin

- .changeset/witty-chefs-sort.md
- packages/astro/package.json
This explains why `npx astro add @spotlighths/astro` didn't work
> fix(astro): Fix type in package.json keywords

- packages/sidecar/package.json
- packages/sidecar/src/connect.js
To hook into Sentry's Node SDK this is what you have to do:
```js
import * as Sentry from '@sentry/node';
import { connect } from '@spotlightjs/sidecar/connect'
Sentry.init({debug: true});
connect(Sentry.getCurrentHub()); // After Sentry init, call connect and pass the hub
...
Sentry.captureMessage('Something went wrong');
```
ref: https://github.com/getsentry/spotlight/issues/76
> feat: Add Sidecar `connect` function

- .changeset/config.json
- package.json
- packages/playground/package.json
- packages/website/CHANGELOG.md
- packages/website/package.json
Remove spotlight- prefix on website and astro-playground.
> Uniform package names

- packages/core/src/components/Trigger.tsx
- packages/core/src/index.tsx
This sets up the toolbar to be extensible with stacked vertical items. It also tweaks the design a bit to give it more room to breath.
Adds new anchor points as well.
> Redesign toolbar to incorporate vertical stack

- .changeset/spotty-seahorses-agree.md
- packages/core/src/App.tsx
- packages/core/src/index.tsx
- packages/core/src/lib/eventTarget.ts
- packages/core/src/types.ts
This is sort of a workaround for #68 which should ensure that even if two spotlight bundle variants end up in the build, still the same event target is used for communication. Not ideal and I'd like to revisit this but for now it should permit opening spotlight in astro apps again (🤞)
> fix(core): Ensure there's only one  global spotlight event target

- .vscode/extensions.json
- packages/website/src/content/docs/about.mdx
- packages/website/src/content/docs/architecture.mdx
- packages/website/src/content/docs/contribute/changesets.mdx
- packages/website/src/content/docs/integrations/build-your-own.mdx
- packages/website/src/content/docs/reference/integration.md
fixes: #135 
- Fixed some typos in docs
- Added a Spell Checker Extension recommendation for vscode.
> fix(docs): typos fixed and added a extension recommendation for vscode

- packages/website/src/content/docs/setup/sentry.mdx
Got to love PRs with one character change! This updates required sentry-ruby version from 5.14 to 5.15.
5.14 shipped today without Spotlight support. So 5.15 is optimistic, assuming we merge https://github.com/getsentry/sentry-ruby/pull/2175 soon enough and ship it.
Welp, saying Spotlight requires a version of SDK that haven't shipped yet is slightly suspicious, but I think it's better than saying things work on 5.14. Plus, there's not a whole lot of people on that website just yet, right? 
/cc @HazAT
> Ruby SDK version requirement: update to 5.15

- packages/overlay/src/components/CardList.tsx
- packages/overlay/src/components/Debugger.tsx
- packages/overlay/src/components/Overview.tsx
- packages/overlay/src/components/SidePanel.tsx
- packages/overlay/src/components/Tabs.tsx
- packages/overlay/src/components/Trigger.tsx
- packages/overlay/src/index.css
- packages/overlay/src/integrations/console/console-tab.tsx
- packages/overlay/src/integrations/sentry/components/EventBreadcrumbs.tsx
- packages/overlay/src/integrations/sentry/components/EventContexts.tsx
- packages/overlay/src/integrations/sentry/components/EventDetails.tsx
- packages/overlay/src/integrations/sentry/components/EventList.tsx
- packages/overlay/src/integrations/sentry/components/Events/Error.tsx
- packages/overlay/src/integrations/sentry/components/Events/Error/Frame.tsx
- packages/overlay/src/integrations/sentry/components/SdkList.tsx
- packages/overlay/src/integrations/sentry/components/SpanDetails.tsx
- packages/overlay/src/integrations/sentry/components/SpanTree.tsx
- packages/overlay/src/integrations/sentry/components/TraceDetails.tsx
- packages/overlay/src/integrations/sentry/components/TraceList.tsx
- packages/overlay/src/integrations/sentry/sentry-integration.ts
- packages/overlay/src/integrations/vite-inspect/vite-inspect.tsx
- packages/overlay/src/sidecar.ts
- packages/overlay/tailwind.config.ts
> enhancement and code refactoring

- .changeset/cool-bears-lie.md
- packages/astro/package.json
- pnpm-lock.yaml
- Add `astro` as a peer dependency. We wanna go with 3.4.0 as the min version due to the dev overlay being added in this version
- Move `astro` to dev dependencies because we don't wanna collide with users' versions and we should only import types anyway
> ref(astro): Add Peer dependencies and move astro to devDependencies

- .changeset/metal-hotels-brake.md
- demos/astro-playground/astro.config.mjs
- demos/astro-playground/src/middleware.ts
- packages/astro/src/index.ts
- packages/astro/src/snippets.ts
This PR refactors hooking into server-side Sentry in astro apps. In contrast to regular Node apps, users don't need to set `spotlight: true` in their Astro SDK because we can simply add the integration in the Astro Spotlight integration. This removes the custom hack we had before that accesses the Sentry client via the global object.
I'll open a follow-up PR to pass a custom sidecar URL to the server snippet
> ref(astro): Use Spotlight integration on server-side instead of custom code

- .changeset/hungry-dryers-hear.md
- .changeset/lucky-fireants-whisper.md
- packages/astro/src/index.ts
- packages/astro/src/snippets.ts
- packages/astro/src/types.ts
- packages/astro/src/vite/error-page.ts
- packages/overlay/src/index.tsx
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/src/integrations/sentry/sentry-integration.ts
Turns out, we didn't yet support custom sidecar urls in the client side integration, meaning client side events didn't get forwarded correctly. This PR now adds support and propagates this support further to the Astro integration. 
This also adds some well-needed cleanup of astro integration types
closes #159 which turned out to be way more complicated than I thought b/c it wasn't yet supported in the overlay
> feat: Add support for custom sidecar URL on client side Sentry integration

- .changeset/friendly-seahorses-compete.md
- packages/overlay/src/App.tsx
- packages/overlay/src/index.tsx
This PR adds two public API callbacks:
- onOpen - fired when the debug window is opened
- onSevereEvent - fired when an integration processes and returns a severe event
> feat(overlay): Add `onOpen` and `onSevereEvent` callbacks

- .changeset/breezy-suns-sell.md
- packages/astro/package.json
see https://github.com/getsentry/sentry-javascript/pull/9696
> chore(astro): Include Astro 4.x preview versions in peer dep range

- packages/website/src/theme.css
This fixes e.g. the card background on hover or certain header elements being too bright
fixes #168
> fix(website): Adjust Starlight `color-gray-7` color value

- packages/astro/src/snippets.ts
- packages/overlay/src/App.tsx
- packages/overlay/src/index.tsx
- packages/overlay/src/sidecar.ts
- packages/overlay/src/types.ts
This PR renames the top level `sidecar` option to `sidecarUrl` because
- the new name much better describes the options purpose
- we use sidecarUrl in the Sentry integrations and in the spotlight sentry integration
> ref(overlay): Rename `sidecar` option to `sidecarUrl`

- .changeset/polite-glasses-add.md
- packages/overlay/src/App.tsx
- packages/overlay/src/index.tsx
- packages/overlay/src/types.ts
- packages/website/src/content/docs/reference/configuration.md
Previously, the name was missleading, suggesting it'd make open the overlay
in fullscreen rather than windowed mode, which it never did.
The only thing this option does is controlling if the overlay window
should be opened immediately when the UI is rendered or if just the
button should be displayed.
> ref(overlay): Rename `fullscreen` option to `openOnInit`

- packages/overlay/src/integrations/sentry/components/SpanDetails.tsx
Previously these values got text color black, now primary-300
> fix(overlay): Adjust text color of span data and context values

- packages/website/src/content/docs/setup/index.mdx
figured it makes sense to use a grid here because eventually this list is gonna become too long and repetetive
before:
after:
> doc(setup): Use grid instead of individual link cards

- packages/website/src/components/FeatureCard.astro
- packages/website/src/components/LandingPage.astro
- packages/website/src/components/codeblock.mdx
added the install command which makes the two other snippets more cohesive but also increases height. 
Appreciate opinions/feedback
before:
after:
> ref(website): Adjust 30 seconds to liftoff

- .changeset/strange-lions-swim.md
- packages/overlay/src/integrations/sentry/components/EventContexts.tsx
- packages/overlay/src/integrations/sentry/components/Tags.tsx
Current state, appreciate input or feel free to take over
closes #177
> feat(overlay): Add tags to error event contexts view

- demos/astro-playground/package.json
- demos/sveltekit/package.json
- packages/website/package.json
- pnpm-lock.yaml
> chore: Bump Sentry SDKs to 7.85.0

- .changeset/gold-numbers-remain.md
- packages/overlay/package.json
- packages/spotlight/package.json
> fix(types): exposed types from overlay

- .changeset/cold-icons-accept.md
- packages/overlay/src/App.tsx
- packages/overlay/src/lib/useKeyPress.ts
closes #218
For now we ignore the MacOS Command key as it requires more modifications to our keypress handler
> fix(overlay): Open overlay on Ctrl+F12 instead of Ctrl/Cmd+Shift+F12

- .changeset/thin-cycles-crash.md
- packages/astro/src/index.ts
Seems like a last minute Astro `4.0.0` stable change caused our previous 4.0.0-beta.4-based check for checking if the dev toolbar is enabled to break. This PR adjusts the check.
> fix(astro): Adjust dev toolbar check after Astro 4.0 stable release

- .changeset/curvy-bobcats-decide.md
🚨 As soon as we merge this, we will need to follow semver and cut minors and majors accordingly!
> meta: Bump `@spotlightjs` packages to version 1.0.0

- packages/website/src/components/sentryCodeBlock.mdx
Try our best to ensure folks don't just load it and ignore that they need a development environment test.
> Make dev env examples more explicit

- packages/website/src/content/docs/reference/configuration.md
Corrected sidecar->sidecarUrl in the docs
> Update configuration.md for sidecarUrl

- .changeset/afraid-rings-divide.md
- .changeset/tasty-rice-camp.md
- packages/sidecar/src/logger.ts
- packages/sidecar/src/main.ts
- packages/sidecar/src/messageBuffer.ts
- packages/sidecar/src/overlay.html
- packages/spotlight/bin/run.js
- packages/spotlight/package.json
- packages/spotlight/src/index.html
- packages/spotlight/vite.overlay.config.ts
- packages/website/astro.config.mjs
- packages/website/package.json
- packages/website/src/content/docs/setup/html.mdx
- packages/website/src/content/docs/sidecar/index.mdx
- packages/website/src/content/docs/sidecar/npx.mdx
- packages/website/src/content/docs/sidecar/vite.mdx
- packages/website/src/content/docs/sidecar/webpack.mdx
- pnpm-lock.yaml
So if you run the Sidecar via the binary now it renders the Overlay in the default route inline
http://localhost:8969
```js
#!/usr/bin/env node
const { setupSidecar } = await import('../dist/sidecar.js');
const port = process.argv[2];
setupSidecar({ port, basePath: process.cwd() });
```
it works by providing a base path to decide where the static files should be served from.
If you run 
```base
$ npx spotlight-sidecar
🔎 [Spotlight] Sidecar listening on 8969
🔎 [Spotlight] You can open: http://localhost:8969 to see the Spotlight overlay directly
```
you can open the url.
https://github.com/getsentry/spotlight/assets/363802/fc3ab8e4-2247-43b3-8a1c-40744340a042
Fixes #244
> Add UI to sidecar

- .changeset/chilly-tigers-swim.md
- packages/overlay/src/assets/chevronDown.svg
- packages/overlay/src/integrations/sentry/components/SpanItem.tsx
- packages/overlay/src/integrations/sentry/components/SpanTree.tsx
fixes: #236 
- collapsed tree after depth of 5
- added a button for every span with children to collapse/expand the tree.
https://vimeo.com/892532538/1448e14bc0?share=copy
> feat(span tree): Added expand/collapse for span item

- .changeset/eight-mangos-complain.md
- packages/overlay/src/integrations/sentry/components/PlatformIcon.tsx
- packages/overlay/src/integrations/sentry/utils/sdkToPlatform.ts
> dotnet logo

- .changeset/light-apes-applaud.md
- packages/sidecar/src/main.ts
With this change, I can merge https://github.com/getsentry/sentry-dotnet/pull/2961 as-is since it relies on all of Sentry's HTTP logic (including retry-after, etc). 
Otherwise I'll need to customize it to deal with 200 or 204, which is fine but since I imagine this might hit other SDKs adding support, changing the status code here might be the simplest.
> return 200 instead of 204 on stream endpoint

- .changeset/many-bears-perform.md
- packages/astro/src/snippets.ts
---
Use `JSON.stringify` when injecting arbitrary paths so it works on Windows (backslashes wont cause problems)
Fix https://github.com/withastro/astro/issues/9389
Astro's fix PR https://github.com/withastro/astro/pull/9400
Spotlight's Astro integration, for some reason, does its own import via vite while registering another import via Astro's Dev Toolbar API. Unfortunately both have the same issue related to absolute path and `\` on Windows. This PR fixes the former while https://github.com/withastro/astro/pull/9400 fixes the latter(not yet landed).
`JSON.stringify` is used in the fix as well as https://github.com/withastro/astro/pull/9400 .
> @spotlightjs/astro: Fix importing arbitrary paths on Windows

- .changeset/sour-boxes-boil.md
- packages/overlay/src/integrations/sentry/components/SpanDetails.tsx
- packages/overlay/src/integrations/sentry/components/SpanItem.tsx
- packages/overlay/src/integrations/sentry/components/SpanTree.tsx
- packages/overlay/src/integrations/sentry/components/TraceDetails.tsx
fixes: #278 
Added a condition to make spanTree collapsible -> in a trace when transactions > 1 || spans >=50
> Added condition to make SpanTree collapsible

- .changeset/spotty-fireants-unite.md
- packages/overlay/src/integrations/sentry/utils/traces.ts
> Fixes sorting of spans accross browsers

- packages/website/src/components/sentryCodeBlock.mdx
Do I need a changeset for this? No package for the website showed for selection.
1.  Moved all snippets back a few characters, has enough padding IMO:
2. Added .NET (not ASP.NET Core or other framework but this should be clear enough):
ASP.NET Core has built-in environment (and env var `ASPNETCORE_ENVIRONMENT` but not referring to it here for simplicity). Also with ASP.NET Core you usr `UseSentry(o => ` instead of `SentrySdk.Init`.
Note the option now is called `EnableSpotlight` not aligning. The option to set a custom URL is `SpotlightUrl`. We could have `Spotlight` as a prop and use `implicit` operators to allow assigning either `string` or `bool` to it but it feels like a hack in C#. I expect us to have more props in the future Spotlight related and wanted to leave `Spotlight` as a …
> install instructions dotnet

- .changeset/orange-points-dress.md
- packages/overlay/src/components/Overview.tsx
- packages/overlay/src/components/Tabs.tsx
- packages/overlay/src/index.css
- packages/overlay/src/index.tsx
Change - 
- instead of scrolling the full page, the header and tabs will now be sticky.
- fixed colors for mobile tab selection
Before
After
> some overlay ui improvements

- .github/workflows/publish.yml
Adds a boolean for each of Docker, NPM, and Electron, to configure manual publishing workflow.
This is useful both in testing as well as resolving errors that may happen during a publish step.
> Add options for each registry for manual publishing

- .changeset/wicked-olives-roll.md
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
#294 
Removed the logic to not reverse the stacktrace of error events when platform is PHP or python.
> fixes: error stacktrace reversing

- packages/website/src/content/docs/setup/nextjs.mdx
- Fix grammar error in description metadata
- Remove SvelteKit reference in next.js doc
> docs(nextjs): Remove SvelteKit reference in next.js doc

- .changeset/itchy-poems-accept.md
- packages/sidecar/src/main.ts
when sidecar already running, process.exit can break the code when setupSidecar is called. removed that.
#333
> fix(sidecar): fixed setupSidecar function to not exit the process when existing sidecar is detected.

- .changeset/soft-tigers-decide.md
- demos/astro-playground/package.json
- demos/sveltekit/package.json
- packages/overlay/src/integrations/sentry/sentry-integration.ts
- packages/website/package.json
- pnpm-lock.yaml
This should fix infinite loops of sentry capturing spotlight requests to the sidecar etc.
I also added some missing volta configs, while at it.
> fix: Use unpatched `fetch` to avoid capturing to Sentry

- .changeset/good-balloons-compete.md
- packages/overlay/src/components/RingChart.tsx
- packages/overlay/src/components/Tabs.tsx
- packages/overlay/src/integrations/sentry/components/Performance/PerformanceTabDetails.tsx
- packages/overlay/src/integrations/sentry/components/Performance/Queries.tsx
- packages/overlay/src/integrations/sentry/components/Performance/QuerySummary.tsx
- packages/overlay/src/integrations/sentry/components/Performance/Resources.tsx
- packages/overlay/src/integrations/sentry/components/Performance/WebVitals/PerformanceChart.tsx
- packages/overlay/src/integrations/sentry/components/Performance/WebVitals/WebVitalsDetail.tsx
- packages/overlay/src/integrations/sentry/components/Performance/WebVitals/index.tsx
- packages/overlay/src/integrations/sentry/components/Performance/WebVitals/utils.ts
- packages/overlay/src/integrations/sentry/constants.ts
- packages/overlay/src/integrations/sentry/hooks/useMouseTracking.ts
- packages/overlay/src/integrations/sentry/types.ts
- packages/overlay/src/integrations/sentry/utils/duration.ts
- packages/overlay/src/integrations/sentry/utils/webVitals.ts
- [] I referenced issues that this PR addresses
Skipped conditions:
1. Since we are not receiving every required metric to calculate the score, we have skipped the condition that prevents the calculation of the performance score in the absence of the necessary metrics. Instead, we are calculating the score with the received metrics.
2. We are consistently using weights and conditions for the Chrome browser because we are not receiving browser information in the event data.
> feat(performance): Web vitals added

- .changeset/old-news-shop.md
- packages/overlay/src/index.tsx
Addresses the hydration error issue in Next.js by ensuring the spotlight is properly reinjected after being removed due to any error.
#339
> fix(overlay): Fix spotlight injection on error removal.

- .changeset/mean-dolls-greet.md
- packages/overlay/package.json
- packages/overlay/src/index.css
- packages/overlay/src/index.tsx
- packages/overlay/src/integrations/hydration-error/HydrationErrorDisplay.tsx
- packages/overlay/src/integrations/hydration-error/index.ts
- pnpm-lock.yaml
#328 
To test the integration please follow these steps:
1. This integration needs a nextjs app.
2. Install and setup the hydration-overlay package - https://github.com/BuilderIO/hydration-overlay
3. Since the integration for spotlight is not yet integrated - use this branch to test - https://github.com/Shubhdeep12/hydration-overlay/tree/feat/spotlight-integration
4. Manipulate `<HydrationOverlay> ` to `<HydrationOverlay integrations={{ spotlight: true }}> `
5. And while initiating Spotlight add a `hydrationError()` integration
Demo
[Screencast from 30-01-24 08:56:11 PM IST.webm](https://github.com/getsentry/spotlight/assets/43654389/978f22a2-e78e-4873-824e-c5ba7c7213c3)
Note: Spotlight integration in hydration-overlay can be tracked …
> feat(integration): Added hydration-overlay integration for nextjs projects

- .changeset/itchy-mice-press.md
- packages/overlay/src/App.tsx
- packages/overlay/src/components/Debugger.tsx
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
- packages/overlay/src/integrations/sentry/data/sentryEventsContext.tsx
- packages/overlay/src/integrations/sentry/data/useSentryEvents.tsx
- packages/sidecar/src/main.ts
#344 
1. Added a DELETE /clear API route for the sidecar to wipe out all data from the buffer.
2. Added a cta in overlay to clear data(only present when sentry integration is added).
[Screencast from 01-02-24 12:31:12 AM IST.webm](https://github.com/getsentry/spotlight/assets/43654389/f2544587-8236-4a72-8d72-f500daed0a86)
> feat(reset): Added functionality in spotlight to reset data.

- .changeset/fair-dingos-hang.md
- packages/overlay/src/integrations/sentry/sentry-integration.ts
This PR drops experimental interaction transactions in the sentry integration's event processor if we determine that they were created from interactions (clicks) within the Spotlight overlay UI. IMO there's no reason to
1. send them to Sentry (only blows up user quota)
2. show them in Spotlight (on the contrary this isn't great UX at all)
So let's just drop these transactions/root spans for now
> fix(overlay): Drop interaction transactions from overlay interactions

- .changeset/old-buckets-call.md
- packages/electron/src/electron/main/index.ts
- packages/electron/src/index.ts
- packages/overlay/src/App.tsx
- packages/overlay/src/components/Debugger.tsx
- packages/overlay/src/index.tsx
- packages/overlay/src/integrations/integration.ts
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/src/types.ts
- packages/sidecar/src/main.ts
- packages/website/src/content/docs/reference/configuration.md
- packages/website/src/content/docs/reference/integration.md
fixes: #350  
1. Removed clear events button for electron app.
2. Added clear events function in Reload and force reload toolbar options in electron app.
3. Created a event listener to clear events data.
4. Added a reset function in integration.
5. Updated the docs and added `reset` function in integration type and `showClearEventsButton` for configuration page
> fix(electron): Clear events button fixes for electron app.

- .changeset/sweet-mangos-knock.md
- packages/overlay/vite.config.ts
For some weird reason when bundling spotlight with webpack - it fails with this:
```
ERROR in ../node_modules/@spotlightjs/overlay/dist/sentry-spotlight.js 22766:11-18
Module not found: Error: Can't resolve 'process/browser' in '/home/runner/work/getsentry/sentry/node_modules/@spotlightjs/overlay/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve 'process/browser' in …
```
> fix: Process webpack build

- packages/website/src/components/sentryCodeBlock.mdx
- packages/website/src/components/sentryCodeBlockMobile.mdx
- packages/website/src/components/sentryCodeBlockWeb.mdx
- packages/website/src/content/docs/integrations/sentry.mdx
- packages/website/src/content/docs/setup/astro.mdx
- packages/website/src/content/docs/setup/other.mdx
- Fixes the link to "Setup Spotlight with Sentry"
- Adds new "Mobile platforms" section with config snippets for Mobile SDKs
- Current snippets are under "Web platforms" section
Putting all snippets in a single tabset was too much, but maybe there's a different/preferred way to solve this.
fixes https://github.com/getsentry/team-mobile/issues/176
> docs(mobile): Add Mobile platform snippets in new section

- .changeset/red-tables-chew.md
- packages/overlay/src/integrations/sentry/components/EventDetails.tsx
- packages/overlay/src/integrations/sentry/components/Performance/Queries.tsx
- packages/overlay/src/integrations/sentry/components/Performance/QuerySummary.tsx
- packages/overlay/src/integrations/sentry/components/Performance/Resources.tsx
- packages/overlay/src/integrations/sentry/components/Performance/WebVitals/WebVitalsDetail.tsx
- packages/overlay/src/integrations/sentry/components/Performance/WebVitals/index.tsx
- packages/overlay/src/integrations/sentry/components/TraceDetails.tsx
#365 
On trace detail page, handled a scenario when trace data is empty. 
It happens when we click on clear events button.
Also, fixed some empty state labels.
> fix(overlay): fixed crashing of overlay on clicking clear events button

- .changeset/great-rings-battle.md
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
issue raised by @lforst on discord - https://discord.com/channels/621778831602221064/1176977569678114847/1222548012937511003
Custom tags added to Sentry are not visible on root spans. 
Reason: While constructing root span for a trace, we used `event.context.trace` but it looks like tags are not up to date here. 
Fix: So for the patch, I've added tags from the event directly, which is up to date. for root custom spans
> fix: Show tags in root spans

- .changeset/tough-melons-hammer.md
- packages/overlay/_fixtures/envelope_php_metrics.txt
- packages/overlay/src/integrations/sentry/index.ts
Earlier, we were skipping the events with the type as "statsd" (metric events). 
Because the type of items received in an envelope was not JSON. 
Now, with this fix, we will assign the string directly instead of parsing if the type is not JSON in the event envelope
> fix(overlay): To display metrics event as well in event envelopes

- .changeset/happy-adults-jam.md
- demos/astro-playground/package.json
- packages/overlay/src/integrations/sentry/index.ts
- pnpm-lock.yaml
Adjusts the global carrier accessing logic to handle the [versioned carrier change](https://github.com/getsentry/sentry-javascript/pull/12206) in version 8.6.0 of the JS SDKs.
I'll look into setting up some more e2e test apps with different SDK versions to cover the logic a bit better.
> feat: Support versioned Sentry carrier object introduced in 8.6.0+

- .changeset/honest-ducks-hang.md
- packages/overlay/src/integrations/sentry/components/traces/TraceDetails.tsx
- packages/overlay/src/integrations/sentry/components/traces/spans/SpanDetails.tsx
- packages/overlay/src/integrations/sentry/components/traces/spans/SpanItem.tsx
- packages/overlay/src/integrations/sentry/components/traces/spans/SpanTree.tsx
fixes: #278 
- Removed the condition to remove collapsing the spans when there is only 1 transaction and <50 spans. Now the spans will always we collapsible.
- Modified condition to auto collapse spans.
- Span will be auto collapsed after depth of 15
- Transaction span will be collapsed when total Transactions are  > 1 and when depth is also not 1 (not collapse the root transaction)
> Fixed the collapsing of spans in trace detail

- packages/website/astro.config.mjs
- packages/website/package.json
- packages/website/sentry.client.config.mjs
- pnpm-lock.yaml
Updates the Sentry Astro SDK from v7 to the latest v8 version. Necessary for the v2 bump of spotlight since we use spotlight in the website
> ref(website): Update to Sentry v8 SDKs

- packages/website/astro.config.mjs
- packages/website/src/content/docs/setup/migration.mdx
Adds a migration guide for Spotlight 1.x -> 2.x
The good news: The only breaking change is the version compatibility range for the Sentry JS SDK. Tried to clarify this in the guide and explicitly mention that the update should be smooth sailing for mobile/backend/non JS SDK users.
[Page Preview](https://spotlightjs-git-lms-feat-website-migration-guide.sentry.dev/setup/migration/)
> doc(website): Add migration guide for updating to 2.x

- packages/website/src/content/docs/contribute/index.mdx
Fixes #220.
I bumped into this issue when trying to get spotlight running locally. Turns out we need an initial build for the playground to work.
> docs: Add build step to initial setup

- packages/astro/src/snippets.ts
The current client init code generation is a bit fragile. It also does not pass the sidecarUrl option to any other potential integrations. This PR fixes that issue and makes the code generation more robust and readable.
> ref: More robust client init code generation

- packages/overlay/src/integrations/sentry/index.ts
In #429, we started sending an empty payload at the start to trigger connect event on Firefox. Our data parser does not account for this and gets confused, causing an error. This patch fixes that.
> fix: Always trim befor trying to JSON.parse

- demos/astro-playground/astro.config.mjs
- demos/astro-playground/package.json
- packages/astro/src/index.ts
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/test/integrations/sentry/data/sentryDataCache.test.ts
- pnpm-lock.yaml
Fixes up #434.
We sometimes load Spotlight befor a Sentry SDK is loaded which
then bails on running the integration with it, making it lose
most of its appeal. To fix this, this PR adds a retry mechanism
which tries detecting Sentry SDK up to 3 times.
This works on the first try if it's just an ordering problem. It
however would not work where a Sentry SDK is loaded on-demand as
we don't have an "on load event" for Sentry SDK.
> fix: Fix ups for the vite-plugin PR

- .changeset/bright-actors-begin.md
- packages/sidecar/src/main.ts
Closes #450. With this, one may use `https://spotlight@localhost:8969/0` as a DSN for an SDK that does not support Spotlight itself.
> feat: Add ability to use Sidecar in a DSN

- .changeset/great-chairs-grab.md
- packages/overlay/package.json
- packages/overlay/src/App.tsx
- packages/overlay/src/constants.ts
- packages/overlay/src/index.tsx
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/src/integrations/sentry/sentry-integration.ts
- packages/sidecar/package.json
- packages/sidecar/src/constants.ts
- packages/sidecar/src/contextlines.ts
- packages/sidecar/src/main.ts
- packages/sidecar/vite.config.ts
- packages/spotlight/package.json
- packages/spotlight/src/vite-plugin.ts
- pnpm-lock.yaml
This change moves the contextlines provider to the sidecar from the Vite plugin opening it up to all SDKs and integrations, not just Vite-based ones. This also means we do not clobber Vite dev server's URL-space (not that it was a problem, but alas).
This required adding a setter to `SentryDataCache` class as it was used as a singleton from its module and handles the additional context line fetching per earlier PRs. It would be good to refactor this usage to make it more contained/encapsulated.
Closes #449.
> feat: Move contextlines code to sidecar

- packages/sidecar/vite.config.ts
- packages/spotlight/vite.config.ts
> ref: Use `module.builtinModules for Vite externals

- .changeset/blue-foxes-serve.md
- packages/spotlight/package.json
Due to a binary name clash between @spotlightjs/spotlight and @spotlightjs/sidecar (which is a dependency of the former), `npx @spotlightjs/spotlight` was running the binary from the sidecar, which does not have the standalone overlay. This PR fixes the issue by renaming the `@spotlightjs/spotlight` binary name to `spotlight` (from `spotlight-sidecar`).
Fixes #385.
> fix: Fix npx @spotlightjs/spotlight

- .github/workflows/prepare-publish.yml
GitHub Actions forbids running subsequent actions for things triggered by the default `GITHUB_TOKEN` to prevent runaway costs. This prevents the builds from running on PRs created by the prepare-publish action, requiring forced-admin priviledgles to merge these PRs due to branch protection rules. This PR switches to the org-wide `GH_RELEASE_PAT` so the CI builds are triggered.
> ci: Use GH_RELEASE_PAT for prepare-publish

- .changeset/chatty-cobras-end.md
- packages/sidecar/package.json
- pnpm-lock.yaml
This was causing crashes as these dependencies were declared as external so needs to be installed.
> fix: Move dependencies from devDependencies for sidecar

- .changeset/lovely-chefs-attend.md
- packages/overlay/src/sidecar.ts
We had multiple logical mistakes, such as not matching on lower-cased content type headers or skipping the entire event handler when a single integration did not define an event processor. This PR fixes these logical issues.
> fix: Fix logical mistakes in integration event processing

- .changeset/loud-melons-rescue.md
- packages/spotlight/src/index.html
This enables the `debug` flag on Spotlight init for debugging.
> feat: Add `#debug` flag to standalone spotlight web UI

- .changeset/pink-buses-burn.md
- packages/sidecar/src/main.ts
This PR automatically corrects Sentry Browser SDK events' content type as it avoids using the standard `application/x-sentry-envelope` for CORS reasons. This also comes with the side effect of fixing URL parsing when it contains a query string or when a content-type header is not set.
> feat: Auto-correct Sentry Browser SDK content type

- .changeset/short-pugs-laugh.md
- .vscode/settings.json
- packages/overlay/src/index.tsx
- packages/overlay/vite.config.ts
- packages/website/src/content/docs/setup/html.mdx
This change adds an Immediately Invoked Function Expression (IIFE) bundle which automatically initializes Spotlight upon loading. Greatly simplifies the HTML include method for Spotlight.
It also fixes a bug where Spotlight won't be initialized if it loads after page `load` event and `injectImmediately` was not set to `true`.
> feat: Add IIFE bundle for single script include

- .github/workflows/publish.yml
As seen from #484, we don't automatically publish to Docker and Electron targets. The reason for this is we have an strict `inputs.docker` and `inputs.electron` check, assuming they will have a default value of `true`. That said the `input` context only gets populated on a manually triggered workflow, hence these jobs get skipped on auto publish actions. This PR should fix the issue by replacing it with an explicit `!= false` check, so it becomes `true` if the value is `null` or `undefined`.
> ci: Fix auto publishing to Docker & Electron

- .changeset/spicy-mayflies-tease.md
- .github/workflows/publish.yml
- packages/electron/electron.vite.config.js
- packages/electron/package.json
- packages/electron/src/electron/main/index.ts
- packages/overlay/vite.config.ts
- pnpm-lock.yaml
This is to fix #484 as we are using a quite old stack (and Electron version).
> fix: Upgrade Electron stack to latest versions

- .changeset/flat-numbers-cheat.md
- packages/electron/src/index.ts
Should fix the last issue with #484
> fix: Fix forgotton Sentry SDK migration in renderer

- .github/workflows/publish.yml
As earlier fixes, since `inputs` context is not available, it comes out as empty which violates the schema of the action we are using as it expects a bool. This patch fixes the issue.
> ci: Fix Docker publish run fail on auto

- packages/overlay/src/App.tsx
- packages/overlay/src/sidecar.ts
This is the first step to send events into Spotlight UI through other means than the sidecar connection.
Related to #133 and #498.
> ref: Refactor sidecar connection code for other sources

- .changeset/nasty-lizards-sleep.md
- .vscode/settings.json
- packages/overlay/src/App.tsx
- packages/overlay/src/index.tsx
- packages/overlay/src/sidecar.ts
Working towards #133, supersedes #498
> feat(overlay): Add direct event sending w/o sidecar

- .gitignore
- packages/astro/src/index.ts
- packages/overlay/src/App.tsx
- packages/overlay/src/index.tsx
- packages/overlay/src/integrations/integration.ts
- packages/overlay/src/integrations/sentry/data/sentryDataCache.spec.ts
- packages/overlay/src/integrations/sentry/index.spec.ts
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/src/integrations/sentry/utils/traces.spec.ts
- packages/overlay/tsconfig.json
- packages/overlay/vitest.config.ts
- packages/sidecar/package.json
- packages/sidecar/tsconfig.json
- packages/spotlight/tsconfig.json
- packages/tsconfig/tsconfig.json
This patch streamlines our `tsconfig`s across packages, always emitting `.d.ts` files (and only them) with using `src` as the root to avoid the `dist/src/something.d.ts` scenario entirely.
Got into this while trying to fix #354 elegantly but failed.
> ref: Fix up some tsconfig schenanigans

- .changeset/stale-jobs-give.md
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
> fix: Stacktraces not reversing when error has full context

- .changeset/big-countries-explode.md
- packages/overlay/src/App.tsx
- packages/overlay/src/lib/db.ts
This pach overhauls the initial rerender with better use of hooks, namely `useCallback` but also using intial state creation function to fix the infinite render loop reported in #521.
Fixes #521.
> fix: Fix infinite render loops for values from DB

- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
We delayed adding an event id to the 'seen' list until we tried to get more context about it, which is an async operation. This causes a race condition where the event was sent multiple times in rapid sucession to show the same event twice.
Fixes #526.
> fix: Mark event as seen as soon as we start processing

- packages/overlay/src/index.tsx
- packages/overlay/src/integrations/sentry/sentry-integration.ts
- packages/overlay/src/types.ts
Adds a `startFrom` init option to control the starting path of Spotlight app. This is useful to immediately display an error when we know will be there. The patch also fixes a bunch of init logic where `__spotlight.initOptions` were not being respected when custom init options are used. It also fixes `sentry()` integration getting initialized even if `integrations` did not include it.
> feat: Add startFrom init option

- packages/website/sentry.client.config.mjs
This is a static website without any confidential information so disable masking for better replays in Sentry.
> chore: Disable Sentry Replay masking on website

- .changeset/famous-olives-argue.md
- packages/overlay/src/components/Trigger.tsx
- packages/website/src/components/Footer.astro
- packages/website/src/components/Header.astro
Fixes #243 
And a minor overlay trigger count issue - when 0 count on trigger we showing 0 with spotlight icon.
> fix: Sentry attribution in docs and overlay trigger minor bug fixed

- .changeset/ten-insects-pull.md
- packages/overlay/src/index.tsx
- packages/spotlight/bin/run.js
- packages/spotlight/src/index.html
- packages/spotlight/vite.config.ts
- packages/spotlight/vite.overlay.config.ts
Fixes #552.
With this change one can now include Spotlight on any page locally from `http://localhost:8969/assets/main.js` (or wherever sidecar is running from).
> feat(spotlight): Stabilize embedded JS filename for external use

- .changeset/big-radios-count.md
- packages/overlay/src/integrations/sentry/components/events/error/Frame.tsx
- packages/overlay/src/integrations/sentry/components/performance/PerformanceTabDetails.tsx
- packages/overlay/src/integrations/sentry/components/traces/spans/SpanDetails.tsx
- Fixed condition for showing open file in editor icon on error frame - missed here https://github.com/getsentry/spotlight/pull/550
- changed route and added navigation in performance tab to make queries tab default active.
- Fixed showing of 0 in false condition in span details
> fix(overlay): UI fixes.

- .changeset/quick-foxes-invent.md
- packages/overlay/src/integrations/sentry/components/performance/Queries.tsx
- packages/overlay/src/integrations/sentry/components/traces/spans/SpanDetails.tsx
- packages/overlay/src/integrations/sentry/constants.ts
> feat(span): Use JsonViewer for JSON-like queries such as MongoDB

- .changeset/nasty-suits-roll.md
- packages/sidecar/src/main.ts
We were calling `server.close()` which only stops new requests from being accepted. It still keeps any open connections, including idle ones for keep-alive. This change forcefully terminates all these connections so the program can exit timely.
> fix: Fix hanging on SIGINT termination

- .changeset/short-wombats-brush.md
- packages/overlay/src/integrations/sentry/components/events/EventList.tsx
- packages/overlay/src/integrations/sentry/components/traces/TraceList.tsx
- packages/overlay/src/integrations/sentry/types.ts
- packages/overlay/src/ui/Tag/Tag.tsx
Fixes #594.
With Astro where we _may_ get the method name in the description already:
With Django SDK where we don't get method name in transaction name:
> feat: Add method name to trace list

- .changeset/neat-dots-learn.md
- demos/astro-playground/sentry.client.config.ts
- packages/overlay/src/integrations/sentry/index.ts
This should enable us to inject Spotlight into live sites through [pure HTML injection](https://spotlightjs.com/setup/html/) for playing around. The change will force-enable tracing to 100% and disables the `DSN` to avoid spamming upstream cloud instance.
> feat: Force-enable tracing with spotlight injection

- .changeset/mean-games-fail.md
- packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/components/TraceDetailHeader.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/components/TraceRootTxnName.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/TraceList.tsx
- packages/overlay/src/ui/Tag/Tag.tsx
> Fix: Trace Root transaction name 

- .changeset/thick-berries-taste.md
- packages/overlay/src/integrations/sentry/index.ts
When testing Spotlight with Sentry's own front-end, I noticed it quite too early and failed to hook into the JS SDK. This patch makes it a bit more graceful with longer delays and up to 10 retries.
> fix(sentry-integration): Make direct SDK link more graceful at the start

- .changeset/popular-kings-wave.md
- packages/overlay/src/App.tsx
- packages/overlay/src/constants.ts
- packages/overlay/src/index.tsx
Fixes #613.
We used to add `overflow: auto` on injection, no matter what. This is bad for a few reasons:
1. Our default is already the closed state, so we should not do anything on initial injection
2. We don't store or know the original value of this style we are touching, which may cause breakage
3. It causes hydration issues as highlighted in #613
This PR injects a special class into the DOM using [adoptedStyleSheets API](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets) on injection and just toggles this class on open/close.
> fix(overlay): Do not modify body styles on injection

- .changeset/large-flies-hunt.md
- packages/spotlight/src/index.html
We were using the default sidecar URL even when Spotlight was started with a different port causing the UI to misbehave and also not connect to the sidecar we just started on the different port. This patch fixes the issue.
> fix(spotlight): Fix UI not working with different port

- .github/workflows/prepare-publish.yml
The `getsentry-release` is a GitHub bot account that is used in various automation, and the `${{ secrets.GH_RELEASE_PAT }}` is a personal access token from that bot account. We are using a regular GitHub account as a bot while it should be a non-human account since there are no humans behind it. Hence, we are replacing it with a GitHub App. 
Functionality wise, there will be no difference. 
More details: https://www.notion.so/sentry/DACI-Replace-GitHub-bot-accounts-with-GitHub-Apps-getsentry-release-15109965d1204a91b9be71c49e8b66e0?pvs=4
#skip-changelog
> feat(release): Replace release bot with GH app

- .changeset/lemon-gorillas-beg.md
- packages/sidecar/src/main.ts
- packages/spotlight/src/index.html
With the previous patch, we assumed the page loads `assets/main.js` is _the_ Spotlight main page which is not the case for auto injection by SDKs (only Django for now but this should expand). This patch fixes the issue by injecting `sentrySpotlightPort` in server-timing headers (yes, hack!)to avoid dynamic HTML generation from sidecar side. I tested that it works and now that it works, we may use this from Django too!
> fix(spotlight): Fix UI not working with different port take 2

- packages/electron/electron.vite.config.js
- packages/electron/src/electron/main/index.ts
- packages/electron/src/index.ts
- packages/spotlight/vite.overlay.config.ts
Currently, we see git SHAs as version names in Sentry for the Electron project. This fix should give us semver versions instead.
> fix: Fix electron version names in Sentry

- .changeset/metal-lies-brush.md
- packages/sidecar/src/main.ts
The `timeout` field we were using is only for socket timeout, causing hanging when there's an unresponsive server running on the same port. This PR fixes that along with the retry logic and its interaction with SIGINT signalling.
Fixes #627.
> fix(sidecar): Fix is sidecar running check timeouts

- packages/website/src/content/docs/reference/configuration.md
This PR fixes a mistyped "open" in spotlight configuration docs page.
> typo: fix mistyped 'open'

- .changeset/cyan-hotels-listen.md
- packages/sidecar/package.json
- pnpm-lock.yaml
> fix(sidecar): Use a newer version of source-map to avoid error

- packages/overlay/src/index.tsx
> fix(overlay): Only init Sentry SDK on fullscreen

- .changeset/thick-lizards-battle.md
- packages/spotlight/bin/instrument.js
- packages/spotlight/bin/run.js
> fix(spotlight): Remove Windows home directories from Sentry reports

- .changeset/new-bats-shake.md
- packages/sidecar/package.json
- pnpm-lock.yaml
The range specified isn't technically correct (pnpm accepts this though). Check with semver
The fix is simple:
```json5
"resolutions": {
"source-map": ">=0.8.0-beta <0.9.0"
},
```
> fix(sidecar): invalid semver range for source-map

- .github/workflows/build.yml
We cannot (and don't need to) push to GHCR from forks.
> ci: Fix Docker Image step fail on forks

- .changeset/plenty-foxes-destroy.md
- .vscode/settings.json
- packages/overlay/src/index.css
- packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanItem.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanTree.tsx
Before:
After:
Before: 
After:
> feat: Less indentation for deep trees with single child

- .changeset/few-points-rush.md
- .github/workflows/build.yml
- .gitignore
- .vscode/settings.json
- demos/astro-playground/astro.config.mjs
- demos/astro-playground/sentry.client.config.ts
- packages/overlay/src/integrations/sentry/components/events/EventList.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/components/TraceTreeview.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/index.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/TraceList.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanItem.tsx
- packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanTree.tsx
- packages/overlay/src/integrations/sentry/data/profiles.ts
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
- packages/overlay/src/integrations/sentry/data/useSentryTraces.ts
- packages/overlay/src/integrations/sentry/index.spec.ts
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/src/integrations/sentry/sentry-integration.ts
- packages/overlay/src/integrations/sentry/types.ts
- packages/overlay/src/integrations/sentry/utils/traces.ts
- packages/overlay/vite.dev.config.ts.timestamp-1738764391518-ec41b9c91387f.mjs
- packages/tsconfig/tsconfig.json
> feat: Start using profile information in span tree

- .changeset/young-moons-cough.md
- packages/overlay/src/integrations/sentry/data/profiles.ts
- packages/overlay/src/integrations/sentry/types.ts
Per https://github.com/getsentry/sentry/blob/55d233c4ac771a876b1dc17a0a0dd330bc7179c8/static/app/types/profiling.d.ts#L119 the `thread_metadata` property is optional, and locally Spotlight now crashes because it's missing for the PHP integration.
> fix(overlay): Process profiles without thread_metadata correctly

- packages/website/astro.config.mjs
- packages/website/src/components/Hero.astro
- packages/website/src/content/docs/about.mdx
- packages/website/src/content/docs/setup/headless.mdx
Its not overly useful to suggest folks download the app when there are additional steps to get Spotlight working.
- Add download actions and a bit of explainer to the about page.
- Add new headless environments setup guide.
> Move download actions into relevant docs

- .changeset/old-fans-brake.md
- packages/overlay/src/ui/SidePanel/SidePanel.tsx
Fixes the inversed logic from #701
> fix: Fix logic in span detail back

- .changeset/lemon-yaks-hammer.md
- packages/overlay/src/integrations/sentry/components/explore/envelopes/EnvelopeDetails.tsx
Fixes #655.
Clicking on the event id now directly downloads it with a `.bin` file extension. We can make this `.txt` but there indeed are binary envelopes that might get corrupted this way.
> feat: Add a way to download raw envelopes

- .changeset/neat-zoos-kiss.md
- packages/overlay/src/integrations/sentry/index.ts
We got a report of an error when we tried to set `sentryClient._options.tracesSampler` implying that `sentryClient._options` might be `null` or `undefined`. This patch adds protection around that.
> fix: Null-check sentryClient._options

- .changeset/big-cheetahs-change.md
- packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanItem.tsx
This helps with crazy rendering times with deep profile trees
> feat: Keep profile spans collapsed

- .changeset/serious-donkeys-try.md
- packages/overlay/src/integrations/sentry/components/events/error/Frame.tsx
Very minor quirk noticed with the stacktrace... node internals were being formatted incorrectly by `formatFilename`, so this change just returns them as is, since they are formatted well to begin with.
before: 
after:
> fix: node filename format was wrong

- packages/website/src/content/docs/contribute/index.mdx
From [contribute docs](https://spotlightjs.com/contribute/):
```bash
VOLTA_FEATURE_PNPM=1
```
This is technically incomplete, so adding `export` makes it a bit more straightforward (just copy/paste from the docs).
> docs: add "export" to VOLTA_FEATURE_PNPM

- .changeset/eight-crews-explain.md
- packages/overlay/src/integrations/sentry/components/explore/envelopes/EnvelopeDetails.tsx
- packages/overlay/src/integrations/sentry/index.ts
- packages/overlay/src/integrations/sentry/utils/bufferParsers.ts
We should parse the envelope data to string while showing raw envelope data.
Earlier
Now
> Fix: Parsing of envelope data

- .changeset/chilled-kangaroos-burn.md
- packages/sidecar/src/main.ts
> feat(sidecar): use nanosecond timestamp for captured filenames

- .changeset/warm-fans-beam.md
- packages/overlay/src/integrations/sentry/data/profiles.ts
- packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
Fixes a race condition where we try to graft a trace which was a skeleton generated from a trace context rather than a full trace. This was causing profile frames not getting grafted as the start_timestamp and timestamp values were not set correctly.
> fix(overlay): Fix eager profile grafting on incomplete trace data

- .changeset/slow-files-invent.md
- packages/overlay/src/integrations/sentry/components/shared/TimeBar.tsx
- The earlier condition could only return 0 or 100 for the percentage
> fix(overlay) round off condition in Timebar

- .changeset/clever-poets-behave.md
- packages/overlay/src/integrations/console/index.ts
- packages/overlay/src/lib/uuid.ts
`window.crypto` API is only available under secure contexts which prevents Spotlight from being used in dev environments w/o https (most of them?). This patch replaces that with our bona fide `generateUuidv4` function. We don't need strong security for these IDs anyway.
> fix(overlay): Don't use `crypto.randomUUID`

- .changeset/strong-phones-nail.md
- packages/overlay/src/integrations/sentry/components/insights/aiTraces/AITraceDetails.tsx
- packages/overlay/src/integrations/sentry/components/insights/aiTraces/AITraceSplitView.tsx
- packages/overlay/src/integrations/sentry/tabs/TracesTab.tsx
#804 was supposed to include this behaviour. Video below:
https://github.com/user-attachments/assets/6c3d02bc-ee54-40b8-b628-c0a05ccde33d
> fix(overlay): Show selected AI trace when clicking on a AI flow item

- .changeset/smart-rabbits-work.md
- .cursor/rules/.cursor/rules/routing.mdc
- packages/overlay/src/integrations/sentry/components/traces/TraceItem.tsx
- packages/overlay/src/integrations/sentry/components/traces/TraceList.tsx
- packages/overlay/src/integrations/sentry/tabs/TracesTab.tsx
I completely destroyed @BYK routing done in #831 . This should restore it.
Added a short cursor rule for routing. I haven't used it yet (I thought about it once I created the PR) but it should be better than not having one.  We could keep adding rules for different topics. 
Next I'll create a hook for traceData as per https://github.com/getsentry/spotlight/pull/831#discussion_r2132878766 to clean up  `TracesTab`
> ref(overlay): Restore routing for traces and spans

- .claude/settings.json
- .mcp.json
- codecov.yml
- Add .claude/settings.json with tool permissions and hooks
- Add .mcp.json for Sentry and Spotlight MCP servers
- Add codecov.yml with informational coverage settings
> feat: add Claude Code settings and MCP configuration

- packages/sidecar/README.md
- packages/sidecar/server.ts
- Replace basic positional argument parsing with Node.js native `parseArgs` utility
- Add proper CLI flags for port and debug mode configuration
- Provide help documentation for CLI users
- **Port flag**: `--port/-p` to set custom port (default: 8969)
- **Debug flag**: `--debug/-d` to enable debug logging
- **Help flag**: `--help/-h` to display usage information
- **Backwards compatibility**: Legacy positional port argument still works
- **Documentation**: Updated README with comprehensive CLI usage examples
Using Node.js native `util.parseArgs()` (stable since Node.js 20) to avoid adding external dependencies while providing a clean, professional CLI experience. The project requires Node.js >= 22, so this native solution is ideal.
> feat(sidecar): improve CLI argument parsing with native parseArgs

- packages/overlay/src/sidecar.ts
- packages/sidecar/src/debugLogging.ts
- packages/sidecar/src/envelopeParser.ts
- packages/sidecar/src/eventContainer.ts
- packages/sidecar/src/logger.ts
- packages/sidecar/src/main.ts
- packages/sidecar/src/mcp/utils/errors.ts
- packages/sidecar/src/mcp/utils/logs.ts
- packages/sidecar/src/userAgent.ts
- packages/sidecar/src/utils.ts
- Implemented EventContainer pattern for lazy parsing of Sentry envelopes
- Enhanced debug logging to show detailed event metadata (SDK, error types, messages)
- Added client identification to track which clients receive events
- **Zero production impact**: Envelopes are only parsed when debug mode is enabled
- **Lazy parsing**: EventContainer caches parsed results to avoid redundant processing
- **Atomic logging**: All related information is logged in single statements for consistency
- **Client identification**: Tracks clients in format `spotlight-overlay/3.2.0 (Chrome; hostname)`
- **Clean output**: Professional logging format with unicode arrows (→ incoming, ← outgoing)
```
→ event | sdk: @sentry/browser | id: abc123
└ error [javascript/production] TypeError: Cannot read property …
```
> feat(sidecar): improve debug logging with detailed event information

- packages/sidecar/README.md
- packages/sidecar/src/mcp/__tests__/test_envelopes.ts
- packages/sidecar/src/mcp/__tests__/traces.test.ts
- packages/sidecar/src/mcp/index.ts
- packages/sidecar/src/mcp/utils/traces.ts
- Adds `get_local_traces` tool to list recent traces with summaries
- Adds `get_events_for_trace` tool to show detailed span trees for specific traces
- Implements hierarchical span tree rendering with proper Unicode characters
This PR implements trace viewing functionality in Spotlight's MCP server, modeled after the sentry-mcp implementation but adapted to Spotlight's architecture.
- **Trace extraction**: Parses Sentry transaction envelopes to extract trace data
- **Hierarchical rendering**: Builds parent-child span trees with proper indentation
- **Orphan handling**: Creates synthetic parent nodes for orphaned spans (matching UI behavior)
- **Unicode tree display**: Uses box-drawing characters (├─, └─, │) for clear visualization
1. First, use `get_local_traces` to see available traces: …
> feat(sidecar): add trace viewing tools to MCP server

- .changeset/silly-bobcats-pay.md
- packages/overlay/src/telemetry/components/insights/Queries.tsx
- packages/overlay/src/telemetry/components/insights/QuerySummary.tsx
- packages/overlay/src/telemetry/components/insights/Resources.tsx
- packages/overlay/src/telemetry/components/insights/envelopes/EnvelopeList.tsx
- packages/overlay/src/telemetry/components/log/LogsList.tsx
- packages/overlay/src/telemetry/components/traces/TraceDetails/index.tsx
- packages/overlay/src/telemetry/data/useSentryEnvelopes.tsx
- packages/overlay/src/telemetry/data/useSentryLogs.tsx
- packages/overlay/src/telemetry/data/useSentrySpans.ts
- packages/overlay/src/telemetry/data/useSpotlightAITraces.ts
- packages/overlay/src/telemetry/tabs/TracesTab.tsx
#924 follow up.
- Replaced destructured usage of `allSpans`, `allTraces`, `allLogs` and `allEnvelopes` from their respective hooks with a direct assignment.
- simplified `errorCount` calculation.
> ref(overlay): small cleanup

- .changeset/major-jokes-rescue.md
- packages/electron/src/electron/main/index.ts
Last week, when removing the overlay feature (and some shadow dom stuff), I renamed the `id` of the app root to `"spotlight-root"` in `packages/overlay/src/index.tsx`:
```typescript
const appRoot = document.createElement("div");
appRoot.id = "spotlight-root";
```
I didn't do a pass on the electron package, missing that the drag feature was based on getting this id.
> electron(fix): draggable electron window

- .changeset/six-adults-return.md
- packages/overlay/src/telemetry/components/insights/envelopes/Attachment.tsx
- packages/overlay/src/telemetry/components/insights/envelopes/EnvelopeDetails.tsx
- packages/overlay/src/telemetry/store/slices/envelopesSlice.ts
- packages/sidecar/src/constants.ts
- packages/sidecar/src/parser/processEnvelope.ts
Supresses parsing errors for statsd and replay_video event types and displays statsd data as text.
> feat: Support for more raw attachment types

- packages/sidecar/src/routes/stream/streaming.ts
Bring back the fix in #429 which got lost during the Hono transition.
> fix: Send something immediately to trigger open event

- packages/overlay/src/telemetry/components/insights/aiTraces/AITraceDetails.tsx
- packages/overlay/src/telemetry/components/insights/aiTraces/sdks/vercelAISDK.ts
- packages/overlay/src/ui/badge.tsx
Closes #966
We supported AI SDK telemetry when they were in beta. Since then, they adopted [opentelemetry gen_ai semantics](https://opentelemetry.io/docs/specs/semconv/gen-ai/gen-ai-spans/) and our SDKs did that too. 
This PR fixes the compatibility with AI SDK.
Tool call view example:
> fix(overlay): Support AI SDK in our AI view
