.changeset/config.json
package.json
pnpm-lock.yaml

This uses the github changelog generator, which is supposed to include commit/pr/user links. Let's see if that works out of the box - it needs a github token, but I guess if we run this on CI we can just use the GITHUB_TOKEN and it should work 🤷

build: Use github changelog generator

---

.github/workflows/deploy.yml
.github/workflows/prepare-publish.yml

TBH not sure if this will actually work, but _seems_ more correct to me - this is failing right now..?

build: update build script

---

.changeset/cyan-donkeys-jump.md
packages/spotlight/src/integrations/sentry/components/SpanDetails.tsx
packages/spotlight/src/integrations/sentry/components/SpanTree.tsx
packages/spotlight/src/integrations/sentry/components/TraceDetails.tsx
packages/spotlight/src/integrations/sentry/tabs/TracesTab.tsx

Moving from navigation via setting ids to navigating with RR

ref(sentry): Use React Router in Traces Tab

---

packages/astro/package.json
packages/astro/src/env.d.ts

oops, typo... we should maybe have some CI step there 😅

fix: Fix package.json

---

.changeset/config.json
package.json
packages/playground/.gitignore
packages/playground/.vscode/extensions.json
packages/playground/.vscode/launch.json
packages/playground/README.md
packages/playground/astro.config.mjs
packages/playground/package.json
packages/playground/src/components/Card.astro
packages/playground/src/components/react/ReactIsland.tsx
packages/playground/src/components/svelte/SvelteIsland.svelte
packages/playground/src/env.d.ts
packages/playground/src/layouts/Layout.astro
packages/playground/src/middleware.ts
packages/playground/src/pages/api/hello.ts
packages/playground/src/pages/index.astro
packages/playground/src/pages/islands/index.astro
packages/playground/src/pages/ssr-error/index.astro
packages/playground/svelte.config.js
packages/playground/tsconfig.json
pnpm-lock.yaml

* add a package to experiment with various errors 
* SSR errors
* island errors
* endpoint errors

chore: Add playground package

---

.changeset/smooth-pandas-press.md
.changeset/warm-countries-own.md
packages/astro/src/vite/source-context.ts
packages/core/src/integrations/sentry/sentry-integration.ts

Just to make this feature a little more robust

ref(stacktrace-symbolication): Guard requests and parsing

---

package.json

Got some pnpm errors when linking the package locally due to a missing name.

Add package name

---

.changeset/strong-beds-thank.md
packages/core/src/App.tsx
packages/core/src/index.tsx
packages/core/src/lib/eventTarget.ts

Maybe something failed (i.e. some sort of deep copy) when passing the target via props to `App.tsx`

fix(core): Use global event target instead of passing it via props

---

packages/core/src/App.tsx
packages/core/src/components/Trigger.tsx
packages/core/src/index.css
packages/core/src/index.tsx

Currently supports bottomLeft and bottomRight (default).

Add configurable trigger anchor location

---

packages/overlay/vitest.config.ts

fixes: #150 
Added aliases for paths in the 'vitest.config.ts' as well, as this was causing test cases to fail.

Fixed failing of test cases.

---

packages/website/src/components/codeblock.mdx
packages/website/src/content/docs/about.mdx
packages/website/src/content/docs/setup/index.mdx

Let's try to avoid footguns to the best of our ability.
Refs GH-144

Improve setup docs to cover Vite/always show dev check

---

packages/website/src/components/LandingPage.astro
packages/website/src/components/codeblock.mdx
packages/website/src/content/docs/about.mdx
packages/website/src/content/docs/contribute/index.mdx
packages/website/src/content/docs/reference/configuration.md
packages/website/src/content/docs/reference/console.mdx
packages/website/src/content/docs/reference/sentry.mdx
packages/website/src/content/docs/setup/index.mdx
packages/website/src/content/docs/sidecar/npx.mdx

- updated landing page
- updated setup
- updated sidecar
- updated contributing
probably missed a few places

ref(docs): Update docs for `@spotlightjs/spotlight`

---

packages/overlay/src/index.tsx
packages/overlay/src/types.ts

added some todos for options refactors

doc(overlay): Add JSDoc to Overlay options

---

packages/website/src/content/docs/about.mdx

Adding context re: hackweek at Sentry

add link to Syntax Hackweek episode

---

packages/website/src/content/docs/setup/astro.mdx

ref(docs): Mention minimum Astro SDK version

---

packages/website/src/content/docs/setup/astro.mdx

Since we were talking a lot about docs 
today, this PR slightly improves the "ramp" 
on our Astro docs.
- better introduction
- steps
- improved wording

ref(docs): Improve Astro setup instructions

---

packages/website/src/content/docs/setup/other.mdx

docs: fix typo on setup/other

---

.changeset/proud-queens-explode.md
packages/overlay/src/components/SidePanel.tsx
packages/overlay/src/integrations/sentry/components/SpanDetails.tsx
packages/overlay/src/types.ts

fixes: #296 
https://vimeo.com/896765309/a91f6c723a?share=copy

closed sidepanel on clicked outside

---

.changeset/sixty-humans-retire.md
packages/electron/index.html
packages/electron/src/electron/main/index.ts
packages/electron/src/types.ts

Electron app enhancements

---

.dockerignore
.github/workflows/publish.yml
.github/workflows/test.yml
Dockerfile
package.json
packages/sidecar/server.js
packages/sidecar/src/main.ts
pnpm-lock.yaml

I wasn't able to get the port fully exposed on WSL2, which I think might be an issue w/ the image. Putting this up as a draft, but also need to figure out where we're publishing it (e.g. to Sentry's org?).
Fixes GH-258

Add docker image for sidecar

---

.github/workflows/publish.yml
.github/workflows/test.yml

Followup to #260, add a docker image that is built for arm64 (both to be used on linux and M1 macOS)

build docker image for arm64

---

.changeset/empty-numbers-drum.md
Dockerfile
packages/spotlight/bin/run.js

used spotlight package in dockerfile instead of just sidecar to serve index file

---

.changeset/beige-beans-eat.md
packages/overlay/src/components/SidePanel.tsx
packages/overlay/src/integrations/sentry/components/Performance/PerformanceTabDetails.tsx
packages/overlay/src/integrations/sentry/components/Performance/Queries.tsx
packages/overlay/src/integrations/sentry/components/Performance/QueryTraces.tsx
packages/overlay/src/integrations/sentry/components/Performance/Resources.tsx
packages/overlay/src/integrations/sentry/components/Performance/WebVitals.tsx
packages/overlay/src/integrations/sentry/components/SpanDetails.tsx
packages/overlay/src/integrations/sentry/data/useSentrySpans.ts
packages/overlay/src/integrations/sentry/index.ts
packages/overlay/src/integrations/sentry/tabs/PerformanceTab.tsx
packages/overlay/src/integrations/sentry/utils/duration.ts
packages/overlay/src/types.ts

#313 
And a prop name fixed- changed from backTo -> backto

feat(performance tab): To capture DB queries on spotlightjs

---

.changeset/large-hotels-speak.md
packages/overlay/src/components/Breadcrumbs.tsx
packages/overlay/src/integrations/sentry/components/Performance/PerformanceTabDetails.tsx
packages/overlay/src/integrations/sentry/components/Performance/Queries.tsx
packages/overlay/src/integrations/sentry/components/Performance/QueryTraces.tsx
packages/overlay/src/integrations/sentry/components/Performance/Resources.tsx
packages/overlay/src/integrations/sentry/components/Performance/WebVitals.tsx
packages/overlay/src/types.ts

Fix: performance tab improvements and generic breadcrumb component added

---

packages/website/src/content/docs/sidecar/vite.mdx

Vite Integration docs for spotlight/sidecar fix.

Vite Integration docs for spotlight/sidecar fix.

---

CONTRIBUTING.md
README.md

docs: Updated README.md and added CONTRIBUTING.md

---

packages/website/src/content/docs/setup/html.mdx
packages/website/src/content/docs/setup/nextjs.mdx
packages/website/src/content/docs/setup/other.mdx
packages/website/src/content/docs/setup/remix.mdx
packages/website/src/content/docs/setup/sveltekit.mdx

fix(docs): made the docs consistent for all frameworks similar to astro

---

packages/website/src/content/docs/setup/remix.mdx

fix(docs): updated spotlight setup in remix app

---

.changeset/fresh-wombats-shout.md
package.json
packages/overlay/src/integrations/sentry/components/developerInfo/EnvelopeList.tsx
packages/overlay/src/integrations/sentry/components/developerInfo/JsonViewer.tsx
packages/overlay/src/integrations/sentry/data/useSentryEnvelopes.tsx
packages/website/src/content/docs/setup/remix.mdx

- fixed the scneario when trace_id is not present like in Metrics event
- Added event type and fixed formatting of envelope info. #382

fix(overlay): Developer info tab fixes

---

.changeset/grumpy-lizards-crash.md
packages/overlay/src/integrations/sentry/components/PlatformIcon.tsx
packages/overlay/src/integrations/sentry/utils/sdkToPlatform.ts

Add Laravel and Symfony platform icons

---

.changeset/pre.json

Plan:
1. merge this PR to exit changeset pre-release mode
2. create `1.x` branch from `main`
3. merge `v2_dev` into `main`
4. Create release (I hope this works as I think it works but we'll see 😅)

publish: Exit changeset pre-release mode

---

packages/website/astro.config.mjs
packages/website/src/content/docs/setup/migration.mdx

adding #413 because I missed the commit while rebasing `v2_dev` 🤦

 doc(website): Add migration guide II

---

packages/sidecar/src/main.ts

fix: Send something immediately to trigger open event

---

.changeset/short-chefs-live.md
packages/overlay/src/integrations/sentry/components/developerInfo/EnvelopeList.tsx
packages/overlay/src/integrations/sentry/components/traces/spans/SpanItem.tsx

Highlighted active span and event

---

packages/overlay/src/integrations/sentry/index.ts

Use Uint8Array as default with `.subarray` instead of `.slice`, mimicking what we do in [`@sentry/utils` code](https://github.com/getsentry/sentry-javascript/blob/f867cc06fb38c1a0f523369210a17684bda223d2/packages/utils/src/envelope.ts#L148).

ref: Simplify and improve envelope parsing

---

.changeset/odd-carrots-work.md
packages/spotlight/tsconfig.json

Fixes #446.
Many thanks to @jarrodldavis.

fix: Fix TypeScript definition locations

---

.github/workflows/test.yml
packages/astro/package.json
packages/sidecar/package.json
packages/spotlight/package.json

ci: Run unit tests for Node 18,20, and 22

---

.github/workflows/publish.yml
packages/electron/package.json

Only build direct dependencies

ref: Smarter electron build

---

.vscode/settings.json
packages/overlay/src/App.tsx
packages/overlay/src/components/Tabs.tsx
packages/overlay/src/lib/useKeyPress.ts

fix: Fix error on autocomplete key presses

---

demos/astro-playground/package.json
demos/sveltekit/package.json
e2e-tests/astro/package.json
packages/electron/package.json
packages/website/package.json
pnpm-lock.yaml

And add some more meta information to Electron package.

chore(deps): Upgrade even moar dependencies

---

packages/overlay/src/integrations/sentry/components/performance/Queries.tsx
packages/overlay/src/integrations/sentry/components/performance/QuerySummary.tsx

Fixes https://github.com/getsentry/spotlight/issues/422 by fixing the DB span regex.

fix(performance): Bring back DB queries info

---

packages/spotlight/bin/run.js

fix(spotlight): Better ascii-art shade

---

.changeset/poor-buckets-explode.md
demos/astro-playground/svelte.config.js
packages/overlay/src/integrations/sentry/components/events/EventContexts.tsx

fix: Contexts inside Trace detail is breaking in case of no child transactions.

---

.changeset/light-trainers-call.md
packages/overlay/src/integrations/sentry/components/events/EventDetails.tsx
packages/overlay/src/integrations/sentry/components/explore/index.tsx
packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/index.tsx
packages/overlay/src/integrations/sentry/components/insights/index.tsx
packages/overlay/src/integrations/sentry/components/insights/webVitals/index.tsx
packages/overlay/src/integrations/sentry/utils/tabs.ts

- Added createTab method
- Removed unwanted onSelect and activeTab values in tabs
- Made whole row clickable in Web vitals

Fix(overlay): Some minor enhancements

---

.changeset/cold-maps-type.md
.vscode/settings.json
packages/overlay/package.json
packages/overlay/src/components/JsonViewer.tsx
pnpm-lock.yaml

fix(overlay): Use a maintained version of rjv

---

.changeset/spicy-monkeys-grab.md
packages/sidecar/package.json
packages/sidecar/server.ts
packages/sidecar/src/vite-plugin.ts
packages/sidecar/vite.config.ts
packages/spotlight/vite.binary.config.ts

fix(sidecar): Revamp build process, export all types

---

.changeset/heavy-monkeys-kneel.md
packages/overlay/vite.config.ts

fix(overlay): Add missing UMD bundle

---

.changeset/calm-crabs-breathe.md
packages/overlay/src/integrations/sentry/components/events/EventBreadcrumbs.tsx
packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/index.tsx
packages/overlay/src/integrations/sentry/types.ts

feat: Add support for rich breadcrumbs

---

.changeset/giant-bugs-suffer.md
package.json
packages/overlay/index.html
packages/overlay/package.json
packages/overlay/vite.config.ts
packages/overlay/vite.dev.config.ts

A little bit copy/pasta and janky but is much better than waiting for the full rebuild cycles + manual refreshes.
This should unblock us and we can then iterate on this a bit for real HMR etc.

dev: Add hot-reload based dev flow

---

.changeset/unlucky-ants-invite.md
packages/electron/src/electron/main/index.ts
packages/electron/src/index.ts
packages/overlay/src/utils/instrumentation.ts
packages/spotlight/bin/instrument.js

fix: Fix revision names in sentry

---

.changeset/grumpy-cheetahs-draw.md
packages/overlay/src/integrations/sentry/constants.ts

fix(overlay): Show all queries

---

packages/website/src/content/docs/setup/other.mdx

docs: Fix relative links

---

.changeset/plenty-lizards-rule.md
packages/overlay/src/integrations/sentry/components/explore/traces/TraceDetails/components/TraceTreeview.tsx
packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanItem.tsx
packages/overlay/src/integrations/sentry/components/explore/traces/spans/SpanTree.tsx
packages/overlay/src/integrations/sentry/context/SearchContext.tsx
packages/overlay/src/integrations/sentry/hooks/useDebounce.ts
packages/overlay/src/integrations/sentry/hooks/useSearchInput.ts

- Added back Search input
- used context for search query(related https://github.com/getsentry/spotlight/pull/424#discussion_r1655526098)
- we can extend this and make a context only for trace detail.
- added a hook for search input

feat: Added Search support in Trace details

---

packages/website/package.json
pnpm-lock.yaml

Hopefully these will fix some random errors that came in to Sentry

chore(website): Upgrade starlight deps

---

packages/sidecar/package.json
packages/sidecar/src/contextlines.ts
pnpm-lock.yaml

chore: Replace source-map packages w/ @jridgewell/source-map

---

packages/website/src/components/Hero.astro
packages/website/src/components/LandingPage.astro
packages/website/src/content/docs/about.mdx
packages/website/src/content/docs/architecture.mdx

Refs #561
Also adds a glow animation to the Spotlight trigger button until it is opened once.

ref(website): Revise "About Spotlight" pieces

---

packages/website/public/install.sh

fix(install): Fix install script on non-Linux

---

.changeset/brave-cobras-cheat.md
packages/sidecar/src/main.ts

fix(sidecar): Handle data capture errors gracefully

---

packages/overlay/src/integrations/sentry/components/events/EventDetails.tsx
packages/overlay/src/integrations/sentry/components/insights/Resources.tsx
packages/overlay/src/integrations/sentry/components/insights/index.tsx

fix?(overlay): UI fixes

---

packages/overlay/src/integrations/sentry/components/events/EventContexts.tsx
packages/overlay/src/integrations/sentry/components/insights/aiTraces/AITraceDetails.tsx
packages/overlay/src/integrations/sentry/components/insights/aiTraces/AITraceList.tsx
packages/overlay/src/integrations/sentry/components/shared/ContextView.tsx
packages/overlay/src/integrations/sentry/components/traces/TraceDetails/components/TraceTreeview.tsx
packages/overlay/src/integrations/sentry/components/traces/TraceDetails/index.tsx
packages/overlay/src/integrations/sentry/components/traces/TraceList.tsx
packages/overlay/src/integrations/sentry/components/traces/spans/SpanDetails.tsx
packages/overlay/src/integrations/sentry/store/slices/eventsSlice.ts
packages/overlay/src/integrations/sentry/store/slices/sharedSlice.ts
packages/overlay/src/integrations/sentry/store/slices/tracesSlice.ts
packages/overlay/src/integrations/sentry/store/types.ts
packages/overlay/src/integrations/sentry/tabs/TracesTab.tsx

fix: Span details view

---

package.json
pnpm-lock.yaml

Fixes https://github.com/getsentry/spotlight/security/dependabot/86

chore: Force form-data to >=4.0.4

---

.changeset/shaggy-rocks-lead.md
packages/overlay/src/App.tsx
packages/overlay/src/components/Debugger.tsx
packages/overlay/src/components/Overview.tsx
packages/overlay/src/index.tsx
packages/overlay/src/integrations/utils/extractPanelsFromIntegrations.ts
packages/overlay/src/overlay/utils/routePersistence.ts

fix(overlay) : routes persistence

---

packages/overlay/src/integrations/sentry/components/insights/Queries.tsx
packages/overlay/src/integrations/sentry/components/insights/Resources.tsx
packages/website/src/content/docs/setup/nextjs.mdx

fix: corrected the highlight position for nextjs setup docs

---

package.json
pnpm-lock.yaml

chore: Make sure devalue is >= 5.3.2

---

.changeset/major-jokes-rescue.md
.changeset/pretty-wasps-fly.md
packages/electron/src/electron/main/index.ts

improved window opening/closing/quitting by the Tray.

fix window opening/closing logic

---

.changeset/wild-hands-beam.md
packages/sidecar/package.json
packages/spotlight/package.json

fix(engines): Fix Node requirment definition to 22

---

packages/website/src/components/MCPHero.astro

Seer knows: https://github.com/getsentry/spotlight/pull/949#discussion_r2379399534

fix(website): Fix potential crash raised in #949

---

packages/overlay/src/index.tsx

fix: s/DEFAULT_SIDECAR_URL/DEFAULT_SIDECAR_STREAM_URL

---

.changeset/many-icons-chew.md
packages/overlay/src/lib/instrumentation.ts
packages/overlay/src/telemetry/components/events/AICopyButton.tsx

feat: sending error from the AI Copy Button to the UI
